#device: "cuda"
#embed_model: "BAAI/bge-large-zh-v1.5"
#llm_model: "Qwen/Qwen1.5-7B-Chat"
#faiss_index_path: "vector_index/faiss_index.index"
#faiss_csv_path: "vector_index/faiss_docs.csv"

embedder:
  model_name: BAAI/bge-large-zh-v1.5
  device: auto

index:
  path: vector_index/faiss_index.index
  docs: vector_index/faiss_docs.csv

llm:
  model_name: Qwen/Qwen3-4B
  device: auto

top_k: 3
max_new_tokens: 200
temperature: 0.7
